# Generated by Creer at 10:46PM on October 16, 2015 UTC, git hash: '98604e3773d1933864742cb78acbf6ea0b4ecd7b'
# This is a simple class to represent the FireDepartment object in the game. You can extend it by adding utility functions here in this file.

from games.anarchy.building import Building

# <<-- Creer-Merge: imports -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
# you can add addtional import(s) here
# <<-- /Creer-Merge: imports -->>

class FireDepartment(Building):
    """ The class representing the FireDepartment in the Anarchy game.

    Can put out fires completely.
    """

    def __init__(self):
        """ initializes a FireDepartment with basic logic as provided by the Creer code generator
        """
        Building.__init__(self)

        # private attributes to hold the properties so they appear read only




    def extinguish(self, building):
        """ Bribes this FireDepartment to extinguish the fire in a building.

        Args:
            building (Building): The Building you want to extinguish.

        Returns:
            bool: true if the bribe worked, false otherwise
        """
        return self._run_on_server('extinguish', building=building)


    # <<-- Creer-Merge: functions -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
    # if you want to add any client side logic (such as state checking functions) this is where you can add them
    # <<-- /Creer-Merge: functions -->>
