# Generated by Creer at 12:13AM on November 01, 2015 UTC, git hash: '1b69e788060071d644dd7b8745dca107577844e1'
# This is a simple class to represent the FireDepartment object in the game. You can extend it by adding utility functions here in this file.

from games.anarchy.building import Building

# <<-- Creer-Merge: imports -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
# you can add addtional import(s) here
# <<-- /Creer-Merge: imports -->>

class FireDepartment(Building):
    """ The class representing the FireDepartment in the Anarchy game.

    Can put out fires completely.
    """

    def __init__(self):
        """ initializes a FireDepartment with basic logic as provided by the Creer code generator
        """
        Building.__init__(self)

        # private attributes to hold the properties so they appear read only
        self._fire_extinguished = 0



    @property
    def fire_extinguished(self):
        """The amount of fire removed from a building when bribed to extinguish a building.
        """
        return self._fire_extinguished



    def extinguish(self, building):
        """ Bribes this FireDepartment to extinguish the some of the fire in a building.

        Args:
            building (Building): The Building you want to extinguish.

        Returns:
            bool: true if the bribe worked, false otherwise
        """
        return self._run_on_server('extinguish', building=building)


    # <<-- Creer-Merge: functions -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
    # if you want to add any client side logic (such as state checking functions) this is where you can add them
    # <<-- /Creer-Merge: functions -->>
