# Generated by Creer at 10:54PM on October 16, 2015 UTC, git hash: '98604e3773d1933864742cb78acbf6ea0b4ecd7b'
# This is a simple class to represent the Player object in the game. You can extend it by adding utility functions here in this file.

from games.anarchy.game_object import GameObject

# <<-- Creer-Merge: imports -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
# you can add addtional import(s) here
# <<-- /Creer-Merge: imports -->>

class Player(GameObject):
    """ The class representing the Player in the Anarchy game.

    A player in this game. Every AI controls one player.
    """

    def __init__(self):
        """ initializes a Player with basic logic as provided by the Creer code generator
        """
        GameObject.__init__(self)

        # private attributes to hold the properties so they appear read only
        self._bribes_remaining = 0
        self._buildings = []
        self._client_type = ""
        self._fire_departments = []
        self._headquarters = None
        self._lost = False
        self._name = "Anonymous"
        self._police_departments = []
        self._reason_lost = ""
        self._reason_won = ""
        self._time_remaining = 0
        self._warehouses = []
        self._weather_stations = []
        self._won = False



    @property
    def bribes_remaining(self):
        """How many bribes this player has remaining to use during their turn. Each action a Building does costs 1 bribe. Any unused bribes are lost at the end of the player's turn.
        """
        return self._bribes_remaining


    @property
    def buildings(self):
        """All the buildings owned by this player.
        """
        return self._buildings


    @property
    def client_type(self):
        """What type of client this is, e.g. 'Python', 'JavaScript', or some other language. For potential data mining purposes.
        """
        return self._client_type


    @property
    def fire_departments(self):
        """All the FireDepartments owned by this player.
        """
        return self._fire_departments


    @property
    def headquarters(self):
        """The Warehouse that serves as this player's headquarters and has extra health. If this gets destroyed they lose.
        """
        return self._headquarters


    @property
    def lost(self):
        """if the player lost the game or not
        """
        return self._lost


    @property
    def name(self):
        """The name of the player
        """
        return self._name


    @property
    def police_departments(self):
        """All the PoliceDepartments owned by this player.
        """
        return self._police_departments


    @property
    def reason_lost(self):
        """the reason why the player lost the game
        """
        return self._reason_lost


    @property
    def reason_won(self):
        """the reason why the player won the game
        """
        return self._reason_won


    @property
    def time_remaining(self):
        """The amount of time (in ns) remaining for this AI to send commands.
        """
        return self._time_remaining


    @property
    def warehouses(self):
        """All the warehouses owned by this player. Includes the Headquarters.
        """
        return self._warehouses


    @property
    def weather_stations(self):
        """All the WeatherStations owned by this player.
        """
        return self._weather_stations


    @property
    def won(self):
        """if the player won the game or not
        """
        return self._won



    # <<-- Creer-Merge: functions -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
    # if you want to add any client side logic (such as state checking functions) this is where you can add them
    # <<-- /Creer-Merge: functions -->>
