# Generated by Creer at 04:13PM on December 01, 2015 UTC, git hash: '1b69e788060071d644dd7b8745dca107577844e1'
# This is a simple class to represent the Game object in the game. You can extend it by adding utility functions here in this file.

from joueur.base_game import BaseGame

# import game objects
from games.chess.game_object import GameObject
from games.chess.piece import Piece
from games.chess.player import Player

# <<-- Creer-Merge: imports -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
# you can add addtional import(s) here
# <<-- /Creer-Merge: imports -->>

class Game(BaseGame):
    """ The class representing the Game in the Chess game.

    The traditional 8x8 chess board with pieces.
    """

    def __init__(self):
        """ initializes a Game with basic logic as provided by the Creer code generator
        """
        BaseGame.__init__(self)

        # private attributes to hold the properties so they appear read only
        self._current_player = None
        self._current_turn = 0
        self._game_objects = {}
        self._max_turns = 100
        self._moves = []
        self._pieces = []
        self._players = []
        self._session = ""
        self._turns_to_stalemate = 0

        self.name = "Chess"

        self._game_object_classes = {
            'GameObject': GameObject,
            'Piece': Piece,
            'Player': Player
        }


    @property
    def current_player(self):
        """The player whose turn it is currently. That player can send commands. Other players cannot.
        """
        return self._current_player


    @property
    def current_turn(self):
        """The current turn number, starting at 0 for the first player's turn
        """
        return self._current_turn


    @property
    def game_objects(self):
        """A mapping of every game object's ID to the actual game object. Primarily used by the server and client to easily refer to the game objects via ID.
        """
        return self._game_objects


    @property
    def max_turns(self):
        """The maximum number of turns before the game will automatically end.
        """
        return self._max_turns


    @property
    def moves(self):
        """ The list of moves in standard algebraic notation (SAN).
        """
        return self._moves


    @property
    def pieces(self):
        """All the uncaptured pieces in the game.
        """
        return self._pieces


    @property
    def players(self):
        """List of all the players in the game.
        """
        return self._players


    @property
    def session(self):
        """A unique identifier for the game instance that is being played.
        """
        return self._session


    @property
    def turns_to_stalemate(self):
        """How many turns until the game ends because no pawn has moved and no piece has been taken
        """
        return self._turns_to_stalemate



    # <<-- Creer-Merge: functions -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
    # if you want to add any client side logic (such as state checking functions) this is where you can add them
    # <<-- /Creer-Merge: functions -->>
