# Generated by Creer at 04:13PM on December 01, 2015 UTC, git hash: '1b69e788060071d644dd7b8745dca107577844e1'
# This is a simple class to represent the Piece object in the game. You can extend it by adding utility functions here in this file.

from games.chess.game_object import GameObject

# <<-- Creer-Merge: imports -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
# you can add addtional import(s) here
# <<-- /Creer-Merge: imports -->>

class Piece(GameObject):
    """ The class representing the Piece in the Chess game.

    A chess piece
    """

    def __init__(self):
        """ initializes a Piece with basic logic as provided by the Creer code generator
        """
        GameObject.__init__(self)

        # private attributes to hold the properties so they appear read only
        self._captured = False
        self._file = 0
        self._has_moved = False
        self._owner = None
        self._rank = ""
        self._type = ""



    @property
    def captured(self):
        """When the piece has been captured (removed from the board) this is true. Otherwise false.
        """
        return self._captured


    @property
    def file(self):
        """The file (y) coordinate of the checker represented as a number [1-8].
        """
        return self._file


    @property
    def has_moved(self):
        """If the piece has moved from its starting position.
        """
        return self._has_moved


    @property
    def owner(self):
        """The player that controls this chess Piece.
        """
        return self._owner


    @property
    def rank(self):
        """The rank (x) coordinate of the checker represented as a letter [a-h].
        """
        return self._rank


    @property
    def type(self):
        """The type of chess piece this is, either: 'King', 'Queen', 'Knight', 'Rook', 'Bishop', or 'Pawn'
        """
        return self._type



    def move(self, rank, file, promotionType=""):
        """ Moves the piece from its current location to the given rank and file.

        Args:
            rank (str): The rank (x) coordinate to move to. Must be [a-h].
            file (int): The file (y) coordinate to move to. Must be [1-8].
            promotion_type (Optional[str]): If this is a Pawn moving to the end of the board then this parameter is what to promote it to.

        Returns:
            str: The standard algebraic notation (SAN) representation of the move if successful, empty string otherwise. In addition if you fail your move you lose.
        """
        return self._run_on_server('move', rank=rank, file=file, promotionType=promotionType)


    # <<-- Creer-Merge: functions -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
    # if you want to add any client side logic (such as state checking functions) this is where you can add them
    # <<-- /Creer-Merge: functions -->>
