# Generated by Creer at 12:33AM on March 01, 2016 UTC, git hash: 'f67dd2eb994fc0ce12bba97b92a5c185ebfa7a5d'
# This is a simple class to represent the Player object in the game. You can extend it by adding utility functions here in this file.

from games.chess.game_object import GameObject

# <<-- Creer-Merge: imports -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
# you can add addtional import(s) here
# <<-- /Creer-Merge: imports -->>

class Player(GameObject):
    """The class representing the Player in the Chess game.

    A player in this game. Every AI controls one player.
    """

    def __init__(self):
        """Initializes a Player with basic logic as provided by the Creer code generator."""
        GameObject.__init__(self)

        # private attributes to hold the properties so they appear read only
        self._client_type = ""
        self._color = ""
        self._in_check = False
        self._lost = False
        self._made_move = False
        self._name = "Anonymous"
        self._other_player = None
        self._pieces = []
        self._rank_direction = 0
        self._reason_lost = ""
        self._reason_won = ""
        self._time_remaining = 0
        self._won = False



    @property
    def client_type(self):
        """What type of client this is, e.g. 'Python', 'JavaScript', or some other language. For potential data mining purposes.

        :rtype: str
        """
        return self._client_type


    @property
    def color(self):
        """The color (side) of this player. Either 'White' or 'Black', with the 'White' player having the first move.

        :rtype: str
        """
        return self._color


    @property
    def in_check(self):
        """True if this player is currently in check, and must move out of check, false otherwise.

        :rtype: bool
        """
        return self._in_check


    @property
    def lost(self):
        """If the player lost the game or not.

        :rtype: bool
        """
        return self._lost


    @property
    def made_move(self):
        """If the Player has made their move for the turn. true means they can no longer move a Piece this turn.

        :rtype: bool
        """
        return self._made_move


    @property
    def name(self):
        """The name of the player.

        :rtype: str
        """
        return self._name


    @property
    def other_player(self):
        """This player's opponent in the game.

        :rtype: Player
        """
        return self._other_player


    @property
    def pieces(self):
        """All the unpcaptured chess Pieces owned by this player.

        :rtype: list[Piece]
        """
        return self._pieces


    @property
    def rank_direction(self):
        """The direction your Pieces must go along the rank axis until they reach the other side.

        :rtype: int
        """
        return self._rank_direction


    @property
    def reason_lost(self):
        """The reason why the player lost the game.

        :rtype: str
        """
        return self._reason_lost


    @property
    def reason_won(self):
        """The reason why the player won the game.

        :rtype: str
        """
        return self._reason_won


    @property
    def time_remaining(self):
        """The amount of time (in ns) remaining for this AI to send commands.

        :rtype: float
        """
        return self._time_remaining


    @property
    def won(self):
        """If the player won the game or not.

        :rtype: bool
        """
        return self._won



    # <<-- Creer-Merge: functions -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
    # if you want to add any client side logic (such as state checking functions) this is where you can add them
    # <<-- /Creer-Merge: functions -->>
