# Generated by Creer at 09:17PM on May 08, 2015 UTC, git hash: '2071c4d66324aad8188edf8c95f4eff08dbda001'
# This is a simple class to represent the Checker object in the game. You can extend it by adding utility functions here in this file.

from Checkers.gameObject import GameObject

# <<-- Creer-Merge: imports -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
# you can add addtional require(s) here
# <<-- /Creer-Merge: imports -->>

class Checker(GameObject):
    """ The class representing the Checker in the Checkers game.

    A checker on the game board.
    """

    def __init__(self, data):
        """ initializes a Checker with basic logic as provided by the Creer code generator

        Args:
            data (dict): initialization data
        """
        GameObject.__init__(self, data)

        # The following values should get overridden when delta states are merged, but we set them here as a reference for you to see what variables this class has.

        # The x coordinate of the checker.
        self.x = 0
        # The player that controls this Checker.
        self.owner = None
        # If the checker has been kinged and can move backwards.
        self.kinged = False
        # The y coordinate of the checker.
        self.y = 0



    def move(self, x, y):
        """ Moves the checker from its current location to the given (x, y).

        Args:
            x (int): The x coordinate to move to.
            y (int): The y coordinate to move to.

        Returns:
            Checker: Returns the same checker that moved if the move was successful. null otherwise.
        """
        return self._run_on_server('move', x=x, y=y)


    def is_mine(self):
        """ returns if the checker is owned by your player or not

        Returns:
            bool: true if it is yours, false if it is not yours
        """
        return self._run_on_server('isMine')


    # <<-- Creer-Merge: functions -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
    # if you want to add any client side logic (such as state checking functions) this is where you can add them
    # <<-- /Creer-Merge: functions -->>
