# Generated by Creer at 02:40AM on May 05, 2015 UTC, git hash: 'Error: git probably not installed'
# This is a simple class to represent the Checker object in the game. You can extend it by adding utility functions here in this file.

from Checkers.gameObject import GameObject


class Checker(GameObject):
    """ The class representing the Checker in the Checkers game.

    A checker on the game board.
    """

    def __init__(self, data):
        """ initializes a Checker with basic logic as provided by the Creer code generator

        Args:
            data (dict): initialization data
        """
        GameObject.__init__(self, data)

        # The following values should get overridden when delta states are merged, but we set them here as a reference for you to see what variables this class has.

        # The x coordinate of the checker.
        self.x = 0
        # The y coordinate of the checker.
        self.y = 0
        # The player that controls this Checker.
        self.owner = None
        # If the checker has been kinged and can move backwards.
        self.kinged = False



    def is_mine(self):
        """ returns if the checker is owned by your player or not

        Returns:
            bool: true if it is yours, false if it is not yours
        """
        return self._run_on_server('isMine')

    def move(self, x, y):
        """ Moves the checker from its current location to the given (x, y).

        Args:
            x (int): The x coordinate to move to.
            y (int): The y coordinate to move to.

        Returns:
            Checker: Returns the same checker that moved if the move was successful. null otherwise.
        """
        return self._run_on_server('move', x=x, y=y)
