# Generated by Creer at 09:17PM on May 08, 2015 UTC, git hash: '2071c4d66324aad8188edf8c95f4eff08dbda001'
# This is a simple class to represent the Game object in the game. You can extend it by adding utility functions here in this file.

from baseGame import BaseGame

# import game objects
from Checkers.gameObject import GameObject
from Checkers.player import Player
from Checkers.checker import Checker

# <<-- Creer-Merge: imports -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
# you can add addtional require(s) here
# <<-- /Creer-Merge: imports -->>

class Game(BaseGame):
    """ The class representing the Game in the Checkers game.

    The simple version of American Checkers. An 8x8 board with 12 checkers on each side that must move diagonally to the opposing side until kinged. Very simple.
    """

    def __init__(self, data):
        """ initializes a Game with basic logic as provided by the Creer code generator

        Args:
            data (dict): initialization data
        """
        BaseGame.__init__(self, data)

        # The following values should get overridden when delta states are merged, but we set them here as a reference for you to see what variables this class has.

        # The maximum number of turns before the game will automatically end.
        self.max_turns = None
        # List of all the players in the game.
        self.players = []
        # The height of the board for the Y component of a checker.
        self.board_height = None
        # The checker that last moved and must be moved because only one checker can move during each players turn.
        self.checker_moved = None
        # The current turn number, starting at 0 for the first player's turn
        self.current_turn = None
        # A mapping of every game object's ID to the actual game object. Primarily used by the server and client to easily refer to the game objects via ID.
        self.game_objects = {}
        # All the checkers currently in the game.
        self.checkers = []
        # The width of the board for X component of a checker.
        self.board_width = None
        # The player whose turn it is currently. That player can send commands. Other players cannot.
        self.current_player = None
        # If the last checker that moved jumped, meaning it can move again.
        self.checker_moved_jumped = False

        self.name = "Checkers"

        self._game_object_classes = {
            'GameObject': GameObject,
            'Player': Player,
            'Checker': Checker
        }


    # <<-- Creer-Merge: functions -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
    # if you want to add any client side logic (such as state checking functions) this is where you can add them
    # <<-- /Creer-Merge: functions -->>
