# Generated by Creer, git hash 1003b60e7d8167f4f73211921de0a0516d97a782
# This is a simple class to represent the Player object in the game. You can extend it by adding utility functions here in this file.

from Checkers.gameObject import GameObject


# @class Player: A player in this game. Every AI controls one player.
class Player(GameObject):
    ## initializes a Player with basic logic as provided by the Creer code generator
    # @param <dict> data: initialization data
    def __init__(self, data):
        GameObject.__init__(self, data)

        self.name = str(data['name'] if 'name' in data else "Anonymous")
        self.win_reason = str(data['winReason'] if 'winReason' in data else "")
        self.won = bool(data['won'] if 'won' in data else False)
        self.time_remaining = int(data['timeRemaining'] if 'timeRemaining' in data else 0)
        self.lost = bool(data['lost'] if 'lost' in data else False)
        self.lose_reason = str(data['loseReason'] if 'loseReason' in data else "")
        self.client_type = str(data['clientType'] if 'clientType' in data else "")



    ## Tells the server that this player is done with their turn.
    def end_turn(self):
        return self.client.send_command(self, 'endTurn')
