# Generated by Creer at 09:17PM on May 08, 2015 UTC, git hash: '2071c4d66324aad8188edf8c95f4eff08dbda001'
# This is a simple class to represent the Player object in the game. You can extend it by adding utility functions here in this file.

from Checkers.gameObject import GameObject

# <<-- Creer-Merge: imports -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
# you can add addtional require(s) here
# <<-- /Creer-Merge: imports -->>

class Player(GameObject):
    """ The class representing the Player in the Checkers game.

    A player in this game. Every AI controls one player.
    """

    def __init__(self, data):
        """ initializes a Player with basic logic as provided by the Creer code generator

        Args:
            data (dict): initialization data
        """
        GameObject.__init__(self, data)

        # The following values should get overridden when delta states are merged, but we set them here as a reference for you to see what variables this class has.

        # if the player won the game or not
        self.won = False
        # What type of client this is, e.g. 'Python', 'JavaScript', or some other language. For potential data mining purposes.
        self.client_type = ""
        # the reason why the player lost the game
        self.reason_lost = ""
        # The name of the player
        self.name = "Anonymous"
        # the reason why the player won the game
        self.reason_won = ""
        # All the checkers currently in the game owned by this player
        self.checkers = []
        # if the player lost the game or not
        self.lost = False
        # The amount of time (in ms) remaining for this AI to send commands.
        self.time_remaining = 0
        # The direction your checkers must go along the y-axis until kinged
        self.y_direction = 0



    # <<-- Creer-Merge: functions -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
    # if you want to add any client side logic (such as state checking functions) this is where you can add them
    # <<-- /Creer-Merge: functions -->>
