# Generated by Creer at 04:24PM on March 02, 2016 UTC, git hash: '0cc14891fb0c7c6bec65a23a8e2497e80f8827c1'
# This is a simple class to represent the Cutter object in the game. You can extend it by adding utility functions here in this file.

from games.spiders.spiderling import Spiderling

# <<-- Creer-Merge: imports -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
# you can add addtional import(s) here
# <<-- /Creer-Merge: imports -->>

class Cutter(Spiderling):
    """The class representing the Cutter in the Spiders game.

    A Spiderling that can cut existing Webs.
    """

    def __init__(self):
        """Initializes a Cutter with basic logic as provided by the Creer code generator."""
        Spiderling.__init__(self)

        # private attributes to hold the properties so they appear read only
        self._cutting_web = None



    @property
    def cutting_web(self):
        """The Web that this Cutter is trying to cut. Null if not cutting.

        :rtype: Nest
        """
        return self._cutting_web



    def cut(self, web):
        """ Cuts a web, destroying it, and any Spiderlings on it.

        Args:
            web (Web): The web you want to Cut. Must be connected to the Nest this Cutter is currently on.

        Returns:
            bool: True if the cut was successfully started, false otherwise.
        """
        return self._run_on_server('cut', web=web)


    # <<-- Creer-Merge: functions -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
    # if you want to add any client side logic (such as state checking functions) this is where you can add them
    # <<-- /Creer-Merge: functions -->>
