# Generated by Creer at 12:46AM on April 16, 2016 UTC, git hash: 'f74143f3f89eebeaa381aba30a8afbda7d0e1d89'
# This is a simple class to represent the Player object in the game. You can extend it by adding utility functions here in this file.

from games.spiders.game_object import GameObject

# <<-- Creer-Merge: imports -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
# you can add addtional import(s) here
# <<-- /Creer-Merge: imports -->>

class Player(GameObject):
    """The class representing the Player in the Spiders game.

    A player in this game. Every AI controls one player.
    """

    def __init__(self):
        """Initializes a Player with basic logic as provided by the Creer code generator."""
        GameObject.__init__(self)

        # private attributes to hold the properties so they appear read only
        self._brood_mother = None
        self._client_type = ""
        self._lost = False
        self._max_spiderlings = 0
        self._name = "Anonymous"
        self._other_player = None
        self._reason_lost = ""
        self._reason_won = ""
        self._spiders = []
        self._time_remaining = 0
        self._won = False



    @property
    def brood_mother(self):
        """This player's BroodMother. If it dies they lose the game.

        :rtype: BroodMother
        """
        return self._brood_mother


    @property
    def client_type(self):
        """What type of client this is, e.g. 'Python', 'JavaScript', or some other language. For potential data mining purposes.

        :rtype: str
        """
        return self._client_type


    @property
    def lost(self):
        """If the player lost the game or not.

        :rtype: bool
        """
        return self._lost


    @property
    def max_spiderlings(self):
        """The max number of Spiderlings players can spawn.

        :rtype: int
        """
        return self._max_spiderlings


    @property
    def name(self):
        """The name of the player.

        :rtype: str
        """
        return self._name


    @property
    def other_player(self):
        """This player's opponent in the game.

        :rtype: Player
        """
        return self._other_player


    @property
    def reason_lost(self):
        """The reason why the player lost the game.

        :rtype: str
        """
        return self._reason_lost


    @property
    def reason_won(self):
        """The reason why the player won the game.

        :rtype: str
        """
        return self._reason_won


    @property
    def spiders(self):
        """All the Spiders owned by this player.

        :rtype: list[Spider]
        """
        return self._spiders


    @property
    def time_remaining(self):
        """The amount of time (in ns) remaining for this AI to send commands.

        :rtype: float
        """
        return self._time_remaining


    @property
    def won(self):
        """If the player won the game or not.

        :rtype: bool
        """
        return self._won



    # <<-- Creer-Merge: functions -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
    # if you want to add any client side logic (such as state checking functions) this is where you can add them
    # <<-- /Creer-Merge: functions -->>
