# Generated by Creer at 02:31PM on October 26, 2015 UTC, git hash: '98604e3773d1933864742cb78acbf6ea0b4ecd7b'
# This is a simple class to represent the Checker object in the game. You can extend it by adding utility functions here in this file.

from games.checkers.game_object import GameObject

# <<-- Creer-Merge: imports -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
# you can add addtional import(s) here
# <<-- /Creer-Merge: imports -->>

class Checker(GameObject):
    """ The class representing the Checker in the Checkers game.

    A checker on the game board.
    """

    def __init__(self):
        """ initializes a Checker with basic logic as provided by the Creer code generator
        """
        GameObject.__init__(self)

        # private attributes to hold the properties so they appear read only
        self._kinged = False
        self._owner = None
        self._x = 0
        self._y = 0



    @property
    def kinged(self):
        """If the checker has been kinged and can move backwards.
        """
        return self._kinged


    @property
    def owner(self):
        """The player that controls this Checker.
        """
        return self._owner


    @property
    def x(self):
        """The x coordinate of the checker.
        """
        return self._x


    @property
    def y(self):
        """The y coordinate of the checker.
        """
        return self._y



    def is_mine(self):
        """ returns if the checker is owned by your player or not

        Returns:
            bool: true if it is yours, false if it is not yours
        """
        return self._run_on_server('isMine')


    def move(self, x, y):
        """ Moves the checker from its current location to the given (x, y).

        Args:
            x (int): The x coordinate to move to.
            y (int): The y coordinate to move to.

        Returns:
            Checker: Returns the same checker that moved if the move was successful. null otherwise.
        """
        return self._run_on_server('move', x=x, y=y)


    # <<-- Creer-Merge: functions -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
    # if you want to add any client side logic (such as state checking functions) this is where you can add them
    # <<-- /Creer-Merge: functions -->>
