# Generated by Creer at 08:44PM on August 10, 2015 UTC, git hash: '44abe78df9634b90415f2d1791a923bdc6e4f5c6'
# This is a simple class to represent the Player object in the game. You can extend it by adding utility functions here in this file.

from games.checkers.game_object import GameObject

# <<-- Creer-Merge: imports -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
# you can add addtional import(s) here
# <<-- /Creer-Merge: imports -->>

class Player(GameObject):
    """ The class representing the Player in the Checkers game.

    A player in this game. Every AI controls one player.
    """

    def __init__(self):
        """ initializes a Player with basic logic as provided by the Creer code generator
        """
        GameObject.__init__(self)

        # The following values should get overridden when delta states are merged, but we set them here as a reference for you to see what variables this class has.

        self._checkers = []
        self._client_type = ""
        self._lost = False
        self._name = "Anonymous"
        self._reason_lost = ""
        self._reason_won = ""
        self._time_remaining = 0
        self._won = False
        self._y_direction = 0



    @property
    def checkers(self):
        """All the checkers currently in the game owned by this player
        """
        return self._checkers


    @property
    def client_type(self):
        """What type of client this is, e.g. 'Python', 'JavaScript', or some other language. For potential data mining purposes.
        """
        return self._client_type


    @property
    def lost(self):
        """if the player lost the game or not
        """
        return self._lost


    @property
    def name(self):
        """The name of the player
        """
        return self._name


    @property
    def reason_lost(self):
        """the reason why the player lost the game
        """
        return self._reason_lost


    @property
    def reason_won(self):
        """the reason why the player won the game
        """
        return self._reason_won


    @property
    def time_remaining(self):
        """The amount of time (in ns) remaining for this AI to send commands.
        """
        return self._time_remaining


    @property
    def won(self):
        """if the player won the game or not
        """
        return self._won


    @property
    def y_direction(self):
        """The direction your checkers must go along the y-axis until kinged
        """
        return self._y_direction



    # <<-- Creer-Merge: functions -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
    # if you want to add any client side logic (such as state checking functions) this is where you can add them
    # <<-- /Creer-Merge: functions -->>
