# Generated by Creer at 07:24PM on February 04, 2016 UTC, git hash: '955970b8006ac45cc438822363db1bc1242d9868'
# This is a simple class to represent the Player object in the game. You can extend it by adding utility functions here in this file.

from games.checkers.game_object import GameObject

# <<-- Creer-Merge: imports -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
# you can add addtional import(s) here
# <<-- /Creer-Merge: imports -->>

class Player(GameObject):
    """The class representing the Player in the Checkers game.

    A player in this game. Every AI controls one player.
    """

    def __init__(self):
        """Initializes a Player with basic logic as provided by the Creer code generator."""
        GameObject.__init__(self)

        # private attributes to hold the properties so they appear read only
        self._checkers = []
        self._client_type = ""
        self._lost = False
        self._name = "Anonymous"
        self._other_player = None
        self._reason_lost = ""
        self._reason_won = ""
        self._time_remaining = 0
        self._won = False
        self._y_direction = 0



    @property
    def checkers(self):
        """All the checkers currently in the game owned by this player

        :rtype: list[Checker]
        """
        return self._checkers


    @property
    def client_type(self):
        """What type of client this is, e.g. 'Python', 'JavaScript', or some other language. For potential data mining purposes.

        :rtype: str
        """
        return self._client_type


    @property
    def lost(self):
        """If the player lost the game or not.

        :rtype: bool
        """
        return self._lost


    @property
    def name(self):
        """The name of the player

        :rtype: str
        """
        return self._name


    @property
    def other_player(self):
        """this player's opponent in the game.

        :rtype: Player
        """
        return self._other_player


    @property
    def reason_lost(self):
        """The reason why the player lost the game.

        :rtype: str
        """
        return self._reason_lost


    @property
    def reason_won(self):
        """The reason why the player won the game.

        :rtype: str
        """
        return self._reason_won


    @property
    def time_remaining(self):
        """The amount of time (in ns) remaining for this AI to send commands.

        :rtype: float
        """
        return self._time_remaining


    @property
    def won(self):
        """If the player won the game or not.

        :rtype: bool
        """
        return self._won


    @property
    def y_direction(self):
        """The direction your checkers must go along the y-axis until kinged

        :rtype: int
        """
        return self._y_direction



    # <<-- Creer-Merge: functions -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
    # if you want to add any client side logic (such as state checking functions) this is where you can add them
    # <<-- /Creer-Merge: functions -->>
